development:
  key: hDMP7EOzwy7osTQsfhcVKw
  secret: Zy8zCmwAqnKhUnqSFzxaUHG09xj3QpCGoZKs6V1xsAI
  access_token: 12897152-eSZ5wwnnmBmUUOcZo0vhDyaEBhKCyQG4tXomDCSSY
  access_token_secret: Ln5aylYdr203a0UNoeeH7KWj7IYgd9l3ANGjPwdORB0Go